### ISSUE TITLE
error build in centos6

### ISSUE THREAD

**Issue by miachel-lv** [jdeng/goheif#12]
I build it on CentOS6, and i get error, here's the log: 
![goheif1](https://user-images.githubusercontent.com/13671739/83394525-54b63e00-a42b-11ea-9bf1-a6307e6afee7.png)
![WechatIMG2372](https://user-images.githubusercontent.com/13671739/83394588-6dbeef00-a42b-11ea-8f9a-0b4bb920ba88.jpeg)
my GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

Hope you can reply me, thanks!

**Comment by jdeng** [comment]
You can update below line in `libde265/libde265.go` by removing `-Wno-constant-conversion`

`//#cgo CXXFLAGS: -Ilibde265 -I. -std=c++11 -Wno-constant-conversion -msse4.1`

**Comment by miachel-lv** [comment]
@jdeng Thank! It's works
