### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by kevinburke** [jdeng/goheif#19]
Hi, does anyone have permission to use this source code? There is not currently a LICENSE attached.

**Comment by grokify** [comment]
> does anyone have permission to use this source code?

The `README.md` indicates this repo includes code from 2 other repos.

> # License
> * heif and libde265 are in their own licenses
> * goheif.go, libde265 golang binding and the heic2jpg utility are in MIT license

Following them indicates 3 licenses are used for the code in this repo.

* `heif` folder is from https://github.com/go4org/go4/tree/master/media/heif, currently Apache 2.0
* `libde265` folder is from https://github.com/strukturag/libde265/tree/master/libde265, currently GNU Lesser General Public License
* Other items are MIT per the README.md
