### ISSUE TITLE
ARM64 linux build failed 

### ISSUE THREAD

**Issue by networkextension** [jdeng/goheif#20]
# github.com/jdeng/goheif/libde265
g++: error: unrecognized command-line option ‘-msse4.1’

**Comment by adrium** [comment]
Can you try, if this fork works: https://github.com/adrium/goheif

**Comment by craigmcdonnell** [comment]
I have tested https://github.com/adrium/goheif as a drop-in replacement for https://github.com/jdeng/goheif and it worked on Mac M1.

Thank you adrium!

**Comment by networkextension** [comment]
https://github.com/adrium/goheif  work great !

**Comment by tagatac** [comment]
This issue isn't really closed on this repo...

@adrium, if this repo is no longer supported, and we are rallying around your fork, can you enable GitHub Issues on it? 🙏

**Comment by adrium** [comment]
Done. I don't know, if I have enough knowledge and capacity to properly maintain it though.
