### ISSUE TITLE
build failed when use vendor and some warnings in cgo 

### ISSUE THREAD

**Issue by brinkpku** [jdeng/goheif#27]
First, I want to thank you for developing and maintaining this project! It has been so beneficial, and I really appreciate the impact it’s had on my work.

## code
<details>
<summary>test code</summary>

```golang 
package main

import (
	"flag"
	"image/jpeg"
	"log"
	"os"

	"github.com/jdeng/goheif"
)

func main() {
	flag.Parse()

	fin, fout := flag.Arg(0), flag.Arg(1)
	fi, err := os.Open(fin)
	if err != nil {
		log.Fatal(err)
	}
	defer fi.Close()

	img, err := goheif.Decode(fi)
	if err != nil {
		log.Fatalf("failed to decode HEIC image: %v", err)
	}

	outFile, err := os.Create(fout)
	if err != nil {
		log.Fatal(err)
	}
	defer outFile.Close()

	err = jpeg.Encode(outFile, img, nil)
	if err != nil {
		log.Fatalf("failed to encode JPEG image: %v", err)
	}
}

```
</details>

## question
1. When build go binary in vendor mod, c++ dependencies in libde265 will not be included in vendor directory. This will lead to build failed.
![screenshot](https://github.com/user-attachments/assets/d083c02c-d147-4b93-af72-0c15a79864ae)

2. After added c++ dependencies to vendor manually, the code can run successfully. However, there are some warnings. 
![screenshot](https://github.com/user-attachments/assets/208ebab3-5df1-4a8d-9649-97dd574090eb)

## enviroment
- os: Ubuntu 20.04.6 LTS
- go version: 1.22.2

## steps to reproduce
1. copy code before
2. init go.mod and download dependency, then run `go mod vendor`
3. run `go main.go <input_pic.heic> <output.jpeg>`, then will reproduce first error
4. copy libde265 depency to vendor directory
5. run `go main.go <input_pic.heic> <output.jpeg>`, then will reproduce second warings

## expected
1. it's better to make dependency included by vendor automatically.
2. those warnings should be fixed.

**Comment by jdeng** [comment]
Added go module support. Now it is clear on Linux.

**Comment by brinkpku** [comment]
> Added go module support. Now it is clear on Linux.

@jdeng The warnings have been fixed. However, I noticed an issue with vendoring C source files when using go mod vendor. I've submitted a pull request [#28](https://github.com/jdeng/goheif/pull/28) to address this problem. Could you please take a look? Thank you!
