### ISSUE TITLE
AppEngine deploy issue

### ISSUE THREAD

**Issue by dimitriadamou** [jdeng/goheif#4]
Hey there, this is a long shot I was unsure if I should put this one here or not

When deploying to app engine Go Build fails with "no buildable Go source files in /go/src/github.com/jdeng/goheif/libde265"

However I can compile / build / run and test the process locally, it just buggers up when I involve App engine deploy for some reason

```
------------------------------------ STDOUT ------------------------------------
building with dependencies from GOPATH
------------------------------------ STDERR ------------------------------------
2019/04/26 13:13:32 staging for go1.11
2019/04/26 13:13:32 Staging second-gen Standard app: failed analyzing /Users/dimitri/Desktop/xxx/service: no buildable Go source files in /go/src/github.com/jdeng/goheif/libde265
GOPATH: /go:/Users/dimitri/Documents/go_appengine:/Users/dimitri/Documents/GoLangExt:/Users/dimitri/go
--------------------------------------------------------------------------------
```

I have definitely checked `/go/src/github.com/jdeng/goheif/libde265` - and as I said my local tests work fine (converts image from heic to jpg)

**Comment by jdeng** [comment]
This sounds like a cgo issue. I haven't used appengine but can you check if there is a place to enable cgo or something like that?
